### ISSUE TITLE
[Nominations Open] Jenkins X Most Valuable Contributor Award 2022 trophy

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x/jx-community#16]
This issue is to receive nominations for the Jenkins X Most Valuable Contributor (MVC) Award 2022.

This award recognizes excellence of contributions to the Jenkins X project, which may be any or a combination of contributions to the documentation, work resolving bugs in the code , implementation of proofs of concepts, advocacy and fostering adoption in other communities.

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to the Jenkins X project and why they should win.
Nomination Deadline: Friday, April 15, 2022

More details are available here: [cd.foundation/cdf-community-awards](https://cd.foundation/cdf-community-awards/)

(Thanks to CDEvents as we used their issue as a template for this (https://github.com/cdevents/spec/issues/33))

**Comment by babadofar** [comment]
Ankit Mohapatra @ankitm123  has really been an outstanding resource in the transition that Jenkins X has gone through, from having a company providing a whole team of developers,  to the current situation where Jenkins X is community driven, with support from the CD foundation. Ankit is always eager to help  people out on Slack, and he has taken a leading role in keeping Jenkins X and the community alive.  We are unsure if Jenkins X even would be alive at this point without his efforts.

**Comment by aabhas-sao** [comment]
> Ankit Mohapatra @ankitm123 has really been an outstanding resource in the transition that Jenkins X has gone through, from having a company providing a whole team of developers, to the current situation where Jenkins X is community driven, with support from the CD foundation. Ankit is always eager to help people out on Slack, and he has taken a leading role in keeping Jenkins X and the community alive. We are unsure if Jenkins X even would be alive at this point without his efforts.

+1. Have to totally agree. @ankitm123 is always there to help people on slack. It's truly inspiring. I really learned a lot about open source spirit from him.

**Comment by rawlingsj** [comment]
+ 1.  Ankit has been outstanding with his contribution to supporting the Jenkins X community and the continuing health of the project.

**Comment by jstrachan** [comment]
`+1` for Ankit from me too!

**Comment by jalonsoa** [comment]
+1 ankit
Mention for @jstrachan who, in my opinion, has been one of the biggest promoters of this project.

**Comment by osamamagdy** [comment]
+1 @ankitm123.
Can't express how helpful he was for me to understand and contribute with Jenkins-X ❤️

**Comment by andynelson** [comment]
+1 for sure

**Comment by zestyroxy** [comment]
+1 @ankitm123  absolutely :)

**Comment by tomhobson** [comment]
I feel it's already been decided, but +1 for @ankitm123
