### ISSUE TITLE
Docs SIG: Find an APAC friendly meeting time

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-community#3]
Our members are based globally, including CA, China, and the EU; bridging all the time zones is very difficult. 

Prior discussion has on the need to find a better time took place on [this issue](https://github.com/jenkins-x/steering/issues/4).

**Comment by MarckK** [comment]
@LinuxSuRen This issue was discussed during Docs SIG meeting today and due to time differences and scheduling conflicts, the best solution may be to create an additional Docs SIG meeting during an APAC friendly time. Wdyt?

What time would work best for you and what cadence? We could hold such a meeting once a month or once a fortnight? Would you be willing to be the host of the meeting?

Please keep in mind that due to time differences and scheduling conflicts not everyone who is a member of the Docs SIG will be able to join.

**Comment by LinuxSuRen** [comment]
It'll be great if we can have an APAC friendly time. My comfortable time does from UTC 10 AM to 2 PM. I can be the host of the meeting during the APAC friendly time.

**Comment by MarckK** [comment]
Awesome @LinuxSuRen! Thank you for hosting the APAC friendly Docs SIG meeting. 😀

Those times would work well for the majority of our SIG members. You are welcome to choose the day, time, and cadence which works best for you. If you raise an issue on the [Jenkins X events calendar page](https://jenkins-x.io/community/calendar/#add-events-or-make-changes) with the meeting time and cadence, and conferencing link, we can add it to the Jenkins X calendar. 🙌

**Comment by MarckK** [comment]
Hi @LinuxSuRen, let me know if you would like me to add an APAC friendly Docs SIG meeting to the Jenkins X calendar.

You can ping me on this issue if that is easier. :-)
